### ISSUE TITLE
Docs - incorrect example path

### ISSUE THREAD

**Issue by adambkaplan** [open-cluster-management-io/multicloud-operators-subscription#313]
**Describe the bug**

In the [git repo subscription](https://github.com/open-cluster-management-io/multicloud-operators-subscription/blob/main/docs/gitrepo_subscription.md) example, the instructions point to an incorrect path.

**To Reproduce**

Try walking through the git repo docs.

**Expected behavior**

Commands as listed work.

**Environment ie: Kubernetes version:**

KinD with Kubernetes 1.25

**Additional context**

N/A

**Comment by mikeshng** [comment]
/assign @lennysgarage 

@lennysgarage could you please help with this one whenever you have some cycles? Not urgent. Thank you!
