### ISSUE TITLE
How can I import subscription in go project by go mod?

### ISSUE THREAD

**Issue by ivan-cai** [open-cluster-management-io/multicloud-operators-subscription#48]
I want reference subscription project in go.mod  such as `	open-cluster-management.io/multicloud-operators-subscription v0.5.0`. But When I try it, I get some errors(`go mod tidy` same as `go get`)：

$ go get open-cluster-management.io/multicloud-operators-subscription           
$ go get: unrecognized import path "open-cluster-management.io/multicloud-operators-subscription": reading https://open-cluster-management.io/multicloud-operators-subscription?go-get=1: 404 Not Found

$ go get github.com/open-cluster-management.io/multicloud-operators-subscription
$ go get: module github.com/open-cluster-management.io/multicloud-operators-subscription: git ls-remote -q origin in /Users/xuejing/go/pkg/mod/cache/vcs/e39fd37dea2cdd2367c5701c5735f384d6cb71d119f0c3fda0c760987fc7c06c: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.

**Comment by ivan-cai** [comment]
I fix this problem by replace.
```
replace (
	k8s.io/client-go => k8s.io/client-go v0.21.3
	open-cluster-management.io/multicloud-operators-subscription => github.com/open-cluster-management-io/multicloud-operators-subscription v0.5.0
)
```

**Comment by mikeshng** [comment]
I need to open a PR against our website to do this redirecting. For example, https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/pull/104
I will get this done asap.

**Comment by mikeshng** [comment]
```
$ go get open-cluster-management.io/multicloud-operators-subscription
go: downloading open-cluster-management.io/multicloud-operators-subscription v0.5.0
```
Fixed now. Feel free to open if you have any more concerns. Thanks.
